# Generated by Django 5.0.3 on 2024-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='Category Slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Category Description')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datetime Modified')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('is_active', '-datetime_created'),
                'indexes': [models.Index(fields=['datetime_created', 'datetime_modified'], name='articles_ca_datetim_8cb452_idx')],
            },
        ),
    ]
