# Generated by Django 5.0.3 on 2024-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Category Name'),
        ),
    ]
