# Generated by Django 5.2.5 on 2025-09-13 00:08

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image.', upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size], verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=255, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'verbose_name': 'Post Translation', 'verbose_name_plural': 'Post Translations'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='topictranslation',
            options={'verbose_name': 'Topic Translation', 'verbose_name_plural': 'Topic Translations'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='datetime_modified',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_at',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='updated_at',
            new_name='datetime_modified',
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topictranslation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_published',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Enter the publish date and time.', null=True, verbose_name='Publish Datetime'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this post active?', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='topictranslation',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topictranslation',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.topic', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter the content of the post.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Enter a brief excerpt of the post.', verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ckb', 'Central Kurdish (Sorani)'), ('ku', 'Northern Kurdish (Kurmanji)')], db_index=True, default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a unique slug.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(help_text='Enter the title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter the topic name.', max_length=255, unique=True, verbose_name='Topic Name'),
        ),
        migrations.AlterField(
            model_name='topictranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('ckb', 'Central Kurdish (Sorani)'), ('ku', 'Northern Kurdish (Kurmanji)')], db_index=True, default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='topictranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a unique slug.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topictranslation',
            name='title',
            field=models.CharField(help_text='Enter the title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='topictranslation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.topic', verbose_name='Topic'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['datetime_published', 'is_active'], name='core_post_datetim_729c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='posttranslation',
            index=models.Index(fields=['post', 'language'], name='core_posttr_post_id_cbcfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='core_topic_name_ed0efc_idx'),
        ),
        migrations.AddIndex(
            model_name='topictranslation',
            index=models.Index(fields=['topic', 'language'], name='core_topict_topic_i_fc6678_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttranslation',
            constraint=models.UniqueConstraint(fields=('post', 'language'), name='unique_post_language'),
        ),
        migrations.AddConstraint(
            model_name='posttranslation',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='unique_language_slug_post'),
        ),
        migrations.AddConstraint(
            model_name='topictranslation',
            constraint=models.UniqueConstraint(fields=('topic', 'language'), name='unique_topic_language'),
        ),
        migrations.AddConstraint(
            model_name='topictranslation',
            constraint=models.UniqueConstraint(fields=('language', 'slug'), name='unique_language_slug_topic'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post', verbose_name='Post'),
        ),
        migrations.RemoveField(
            model_name='posttranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='posttranslation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topictranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topictranslation',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'created_at'], name='core_postim_post_id_c8d54b_idx'),
        ),
    ]
