# Generated by Django 5.2.5 on 2025-09-13 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postimage_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Select the author of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=True, help_text='Allow comments on this post.', verbose_name='Comments Enabled'),
        ),
        migrations.AddField(
            model_name='post',
            name='discussion_status',
            field=models.BooleanField(default=True, help_text='Allow discussions on this post.', verbose_name='Discussion Enabled'),
        ),
        migrations.AddField(
            model_name='post',
            name='revision_status',
            field=models.BooleanField(default=True, help_text='Enable revisions for this post.', verbose_name='Revisions Enabled'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Writing'), ('3', 'Review'), ('4', 'Published')], db_index=True, default='1', help_text='Select the status of the post.', max_length=1, verbose_name='Status'),
        ),
    ]
