# Generated by Django 5.2.5 on 2025-09-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tempimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempImage',
        ),
    ]
