# Generated by Django 5.2.3 on 2025-06-27 04:55

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict, help_text='Title and description for different languages, stored as JSON.', validators=[pages.models._validate_content], verbose_name='Content')),
                ('image', models.ImageField(help_text='Image for the index page.', upload_to='pages/images/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Only one IndexPage can be active at a time.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Index Page',
                'verbose_name_plural': 'Index Pages',
            },
        ),
    ]
