# Generated by Django 5.1.8 on 2025-04-13 15:38

import django_tiptap.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_header_image', models.ImageField(default='defaults/pages/headers/index_default_header.webp', help_text='Upload a header image for the index/home page.', upload_to='pages/headers/', verbose_name='Main Header Image')),
                ('index_page_title', models.CharField(max_length=255, verbose_name="'Index/Home' Page Title")),
                ('index_page_moving_slogan_text', models.CharField(help_text='This text will be displayed as a moving slogan.', max_length=255, verbose_name='Moving Slogan Text')),
                ('about_us_page_header_image', models.ImageField(default='defaults/pages/headers/about_us_default_header.webp', help_text="Upload a header image for the 'About Us' page.", upload_to='pages/headers/', verbose_name='About Us Header Image')),
                ('about_us_page_title', models.CharField(max_length=255, verbose_name="'About Us' Page Title")),
                ('about_us_page_content', django_tiptap.fields.TipTapTextField()),
            ],
        ),
    ]
