# Generated by Django 5.1.8 on 2025-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='index_page_moving_slogan_text',
            field=models.CharField(default='Welcome to Auditorium: The Opinions & Ideas Open Source project.', help_text='This text will be displayed as a moving slogan.', max_length=255, verbose_name='Moving Slogan Text'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='index_page_title',
            field=models.CharField(default='Index: Auditorium', max_length=255, verbose_name="'Index/Home' Page Title"),
        ),
    ]
