# Generated by Django 5.1.8 on 2025-04-13 15:59

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_about_us_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='about_us_page_content',
            field=django_quill.fields.QuillField(),
        ),
    ]
