# Generated by Django 5.1.8 on 2025-04-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagetranslation_index_page_moving_slogan_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
