# Generated by Django 5.1.8 on 2025-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='index_page_background_title',
            field=models.CharField(default='GRIEVE & GRIEF', help_text='This text will be displayed as a background title.', max_length=255, verbose_name='Background Title'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='index_page_introduction_subtitle',
            field=models.CharField(default='Welcome to AUDITORIUM — a sanctuary, a safe house for thoughts, articles, reflections, and everything your mind dares to put to the paper of this project.', max_length=1024, verbose_name="'Index/Home' Page Introduction Subtitle"),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='index_page_introduction_title',
            field=models.CharField(default="HELLO TO THE 'BIG STEPPER.'", max_length=255, verbose_name="'Index/Home' Page Introduction Title"),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activation Status'),
        ),
    ]
