# Generated by Django 5.1.8 on 2025-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagetranslation_index_page_background_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetranslation',
            name='index_page_moving_slogan_text',
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='index_page_moving_slogan_text_1',
            field=models.CharField(default='Welcome to Auditorium: The Opinions & Ideas Open Source project.', help_text="This text will be displayed as a moving slogan. (it's the first one)", max_length=255, verbose_name='Moving Slogan Text'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='index_page_moving_slogan_text_2',
            field=models.CharField(default='Hello to the big stepper, never losing count.', help_text="This text will be displayed as a moving slogan (it's the second one).", max_length=255, verbose_name='Moving Slogan Text'),
        ),
    ]
