# Generated by Django 5.1.8 on 2025-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sentences_sentencestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='index_page_sentences',
            field=models.ManyToManyField(blank=True, help_text='These sentences will be displayed on the index page.', related_name='index_page_sentences', to='pages.sentences', verbose_name='Index Page Sentences'),
        ),
    ]
