# Generated by Django 5.1.8 on 2025-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_index_page_sentences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetranslation',
            old_name='about_us_page_content',
            new_name='about_page_content',
        ),
        migrations.RenameField(
            model_name='pagetranslation',
            old_name='about_us_page_title',
            new_name='about_page_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='about_us_page_header_image',
        ),
        migrations.AddField(
            model_name='page',
            name='about_page_header_image',
            field=models.ImageField(blank=True, default='defaults/pages/headers/about_us_default_header.webp', help_text="Upload a header image for the 'About' page.", null=True, upload_to='pages/headers/', verbose_name='About Header Image'),
        ),
    ]
