# Generated by Django 5.1.8 on 2025-04-16 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_about_us_page_content_pagetranslation_about_page_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='about_page_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This text will be displayed as the content of the 'About' page.", null=True, verbose_name="'About' Page Content"),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='about_page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="'About' Page Title"),
        ),
    ]
