# Generated by Django 5.1.8 on 2025-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pagetranslation_about_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='about_page_introduction_background_title',
            field=models.CharField(blank=True, help_text="This text will be displayed as the background title of the 'About' page.", max_length=255, null=True, verbose_name="'About' Page Background Title"),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='about_page_introduction_title',
            field=models.CharField(blank=True, help_text="This text will be displayed as the introduction title of the 'About' page.", max_length=255, null=True, verbose_name="'About' Page Introduction Title"),
        ),
    ]
