# Generated by Django 5.1.8 on 2025-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_pagetranslation_about_page_introduction_background_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='about_page_header_image',
            field=models.ImageField(blank=True, default='defaults/pages/headers/about_default_header_image.webp', help_text="Upload a header image for the 'About' page.", null=True, upload_to='pages/headers/', verbose_name='About Header Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='index_page_header_image',
            field=models.ImageField(blank=True, default='defaults/pages/headers/index_default_header_image.webp', help_text='Upload a header image for the index/home page.', null=True, upload_to='pages/headers/', verbose_name='Main Header Image'),
        ),
    ]
