# Generated by Django 5.1.8 on 2025-04-25 14:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', accounts.models.TranslatableUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default=None, help_text='Select an avatar for your profile.', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
