# Generated by Django 5.1.8 on 2025-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_ckb',
            field=models.CharField(blank=True, help_text='A short biography for the user.', max_length=525, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_en',
            field=models.CharField(blank=True, help_text='A short biography for the user.', max_length=525, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_fa',
            field=models.CharField(blank=True, help_text='A short biography for the user.', max_length=525, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_ku',
            field=models.CharField(blank=True, help_text='A short biography for the user.', max_length=525, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ckb',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ku',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ckb',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ku',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar11.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
