# Generated by Django 5.0.3 on 2024-03-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='constants/<function set_random_user_avatar at 0xffff8fe5e8e0>.webp', upload_to='accounts/avatars/', verbose_name='Avatars'),
        ),
    ]
