# Generated by Django 5.1.8 on 2025-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/accounts/avatars/avatar_4.webp', help_text='Select an avatar for your profile.', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email address.', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
