# Generated by Django 5.1.8 on 2025-06-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_ckb_user_bio_en_user_bio_fa_user_bio_ku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio_ku',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_ku',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ku',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar19.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
