# Generated by Django 5.1.8 on 2025-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_avatar_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/accounts/avatars/avatar_2.webp', help_text='Select an avatar for your profile.', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
