# Generated by Django 5.1.8 on 2025-06-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_bio_ku_remove_user_first_name_ku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio_ckb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio_fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_ckb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ckb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_fa',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar18.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
