# Generated by Django 5.1.8 on 2025-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='banner',
            field=models.ImageField(blank=True, default='defaults/accounts/banners/default_banner.webp', help_text='Select a banner for your profile.', null=True, upload_to='banners/', verbose_name='Banner'),
        ),
    ]
