# Generated by Django 5.2.3 on 2025-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar_userprofilei18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profiles',
            field=models.JSONField(default=dict, help_text='Name and bio for different languages, stored as JSON.', verbose_name='Name and Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar10.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.DeleteModel(
            name='UserProfileI18n',
        ),
    ]
