# Generated by Django 5.1.8 on 2025-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='banner',
        ),
    ]
