# Generated by Django 5.2.3 on 2025-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profiles_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar_2.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
