# Generated by Django 5.2.3 on 2025-07-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_verified_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='is_for_token',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/avatar_7.webp', help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
