# Generated by Django 5.2.3 on 2025-08-01 08:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverificationcode_is_for_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Attempt Count'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lockout Until'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='is_for_token',
            field=models.BooleanField(default=True, help_text='True for link-based, False for 10-digit code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=accounts.models._set_user_random_avatar, help_text='Upload a profile picture for the user.', upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='/static/shared/banners/default_banner.webp', help_text='Upload a banner image for the user profile.', upload_to='banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profiles',
            field=models.JSONField(default=accounts.models.get_default_profiles, help_text='Name and bio for different languages, stored as JSON.', verbose_name='Name and Bio'),
        ),
    ]
