# Generated by Django 5.2.3 on 2025-08-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCode',
        ),
    ]
