# Generated by Django 5.2.3 on 2025-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_logincode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'ordering': ['-expires_at']},
        ),
        migrations.RemoveField(
            model_name='logincode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='logincode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logincode',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
