# Generated by Django 5.2.3 on 2025-08-12 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_logincode_options_remove_logincode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={},
        ),
        migrations.RemoveField(
            model_name='logincode',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='logincode',
            name='lockout_until',
        ),
        migrations.AddField(
            model_name='logincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
