# Generated by Django 5.2.3 on 2025-08-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_logincode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Attempt Count'),
        ),
        migrations.AddField(
            model_name='logincode',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lockout Until'),
        ),
    ]
