# Generated by Django 5.2.3 on 2025-08-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_logincode_attempt_count_logincode_lockout_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincode',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='logincode',
            name='lockout_until',
        ),
    ]
