# Generated by Django 5.2.3 on 2025-08-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_logincode_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Enter a valid email address.', 'unique': 'A user with that email already exists.'}, help_text='Enter a valid email address. This will be used for account verification and notifications.', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
