# Generated by Django 5.2.3 on 2025-08-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address. This will be used for account verification and notifications.', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
