# Generated by Django 5.2.5 on 2025-09-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginCode',
            new_name='AuditoCode',
        ),
    ]
