# Generated by Django 5.2.5 on 2025-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_logincode_auditocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditocode',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('password', 'Password Change')], default='login', max_length=20),
        ),
    ]
