# Generated by Django 5.2.5 on 2025-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auditocode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_history',
            field=models.JSONField(default=list, help_text='Stores the last 5 passwords used.', verbose_name='Password History'),
        ),
    ]
