# Generated by Django 5.2.5 on 2025-09-09 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English (United States)'), ('fa', 'Persian (Farsi)'), ('ckb', 'Central Kurdish (Sorani Kurdish)'), ('ku', 'Northern Kurdish (Kurmanji Kurdish)')], default='en', max_length=10, verbose_name='Language')),
                ('theme', models.CharField(choices=[('DL', 'Default Light'), ('DD', 'Default Dark')], default='DL', max_length=20, verbose_name='Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
