# Generated by Django 5.2.5 on 2025-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('DA', 'Default Auto'), ('DL', 'Default Light'), ('DD', 'Default Dark')], default='DA', max_length=20, verbose_name='Theme'),
        ),
    ]
