# Generated by Django 5.2.5 on 2025-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_alter_settings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='Enable Notifications'),
        ),
        migrations.AddField(
            model_name='settings',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=16, help_text='Font size in pixels (12-24)', verbose_name='Font Size'),
        ),
    ]
