# Generated by Django 5.2.5 on 2025-09-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_settings_enable_notifications_settings_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_particles',
            field=models.BooleanField(default=False, verbose_name='Enable Particles Effect'),
        ),
    ]
