# Generated by Django 5.1.8 on 2025-04-27 15:00

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ImageField(blank=True, default='documents/halls/default.jpg', upload_to='documents/halls/', verbose_name='Artwork')),
                ('slug', models.SlugField(help_text='Slug for the hall. Used in the URL.', max_length=255, unique=True, verbose_name='Slug')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date and time when the hall was created.', verbose_name='Created At')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='Date and time when the hall was last updated.', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('0', 'Idea'), ('1', 'Activated')], default='0', help_text='Status of the hall.', max_length=1, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, help_text='Is the hall active?', verbose_name='Activation Status')),
                ('is_explicit', models.BooleanField(default=False, help_text='Is the hall explicit? Is it has explicit content?', verbose_name='Explicit Content')),
                ('is_sequential', models.BooleanField(default=False, help_text='This room contains sequential posts, and the posts will be related to each other.', verbose_name='Sequential Posts')),
                ('creator', models.ForeignKey(help_text='Creator of the hall.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent hall of the current hall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.hall', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ImageField(blank=True, default='documents/artworks/default.jpg', help_text='Artwork for the post.', null=True, upload_to='documents/artworks/', verbose_name='Artwork')),
                ('slug', models.SlugField(help_text='Slug for the post. Used in the URL.', max_length=255, unique=True, verbose_name='Slug')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was created.', verbose_name='Created At')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Date and time when the post was last updated.', verbose_name='Updated At')),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the post was published.', verbose_name='Published At')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', help_text='Status of the post.', max_length=1, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the post active?', verbose_name='Activation Status')),
                ('is_explicit', models.BooleanField(default=False, help_text='Is the post explicit? Is it has explicit content?', verbose_name='Explicit Content')),
                ('author', models.ForeignKey(help_text='Author of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('hall', models.ForeignKey(help_text='Hall of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_posts', to='documents.hall', verbose_name='Hall')),
                ('views', models.ManyToManyField(blank=True, help_text='This field shows how many people watched this post.', to='engine.ipaddress', verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publish_datetime'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HallTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='Name of the hall.', max_length=255, verbose_name='Name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Description of the hall.', verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.hall')),
            ],
            options={
                'verbose_name': 'Hall Translation',
                'db_table': 'documents_hall_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Title of the post.', max_length=255, verbose_name='Title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Content of the post.', verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.post')),
            ],
            options={
                'verbose_name': 'Post Translation',
                'db_table': 'documents_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
