# Generated by Django 5.1.8 on 2025-04-18 19:11

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ImageField(blank=True, default='documents/artworks/default.jpg', help_text='Artwork for the post.', null=True, upload_to='documents/artworks/', verbose_name='Artwork')),
                ('slug', models.SlugField(help_text='Slug for the post. Used in the URL.', max_length=255, unique=True, verbose_name='Slug')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was created.', verbose_name='Created At')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='Date and time when the post was last updated.', verbose_name='Updated At')),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the post was published.', verbose_name='Published At')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', help_text='Status of the post.', max_length=1, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the post active?', verbose_name='Activation Status')),
                ('author', models.ForeignKey(help_text='Author of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publish_datetime'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Title of the post.', max_length=255, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.post')),
            ],
            options={
                'verbose_name': 'Post Translation',
                'db_table': 'documents_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
