# Generated by Django 5.1.8 on 2025-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='explicit',
            new_name='is_explicit',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='explicit',
            new_name='is_explicit',
        ),
        migrations.AddField(
            model_name='hall',
            name='is_sequential',
            field=models.BooleanField(default=False, help_text='This room contains sequential posts, and the posts will be related to each other.', verbose_name='Sequential Posts'),
        ),
    ]
