# Generated by Django 5.1.8 on 2025-04-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explicit',
            field=models.BooleanField(default=False, help_text='Is the post explicit? Is it has explicit content?', verbose_name='Explicit Content'),
        ),
    ]
