# Generated by Django 5.1.8 on 2025-04-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='halltranslation',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of the hall', max_length=225, null=True, verbose_name='Subtitle'),
        ),
    ]
