# Generated by Django 5.1.8 on 2025-04-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_halltranslation_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent hall of the current hall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.hall', verbose_name='Parent'),
        ),
    ]
