# Generated by Django 5.1.8 on 2025-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_hall_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pinned'),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pinned'),
        ),
    ]
