# Generated by Django 5.1.8 on 2025-04-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_post_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='documents_p_search__e64de7_idx',
        ),
    ]
