# Generated by Django 5.1.8 on 2025-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user.', unique=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the IP address was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
            },
        ),
    ]
